name: Lists
main: com.herocraftonline.dthielke.lists.Lists
version: 0.1.0
description: Basic player list API for other plugins to make use of.
commands:
  ls:
    description: Lists commands
    usage: /ls <command>